# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['caption'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('content', models.ImageField(upload_to='videos')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['caption'],
            },
        ),
    ]
